yaml
name: ETF Trading Bot

on:
  schedule:
    # Vsak dan ob 9:00, 13:00, 17:00 ET (14:00, 18:00, 22:00 UTC)
    - cron: '0 14,18,22 * * 1-5'  # Pon-Pet
  workflow_dispatch:  # Omogoči ročni zagon

jobs:
  run-bot:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install yfinance pandas numpy
        
    - name: Run ETF Bot
      env:
        EMAIL: ${{ secrets.EMAIL }}
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python etf_bot.py
